name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.2.0-dev.6
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  x509: ^0.2.4
  jose: ^0.3.4
  dotenv: ^4.2.0
  openid_client: ^0.4.8
  firebase_dart: ^1.1.2
  path: ^1.9.0
  meta: ^1.11.0
  http: ^1.2.0
  crypto_keys: ^0.3.0+1
  collection: ^1.18.0
  gcloud: ^0.8.12

dev_dependencies:
  test: ^1.25.1
  fake_async: ^1.3.1
  lints: ^3.0.0
  mockito: ^5.4.4
